name: Build

on:
  pull_request:
    branches: [ main, dev, qa, release ]
  push:
    branches: [ main, dev, qa, release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --coverage